<?php
declare(strict_types=1);

namespace WYSiteIWYG;

use RuntimeException;

final class SiteGenerator
{
    private string $rootPath;
    private BlockRepository $repository;
    private ThemeManager $themes;
    private string $siteBaseUrl;

    public function __construct(string $rootPath, BlockRepository $repository, ThemeManager $themes, string $siteBaseUrl = '/')
    {
        $this->rootPath = rtrim($rootPath, '/');
        $this->repository = $repository;
        $this->themes = $themes;
        $this->siteBaseUrl = '/' . trim($siteBaseUrl, '/');
        $this->siteBaseUrl = $this->siteBaseUrl === '/' ? '/' : $this->siteBaseUrl . '/';
    }

    public function createPage(string $title, string $slug): string
    {
        $title = trim($title);
        $slug = $this->normalizeSlug($slug !== '' ? $slug : $title);
        $path = $slug === 'index' ? 'index.html' : $slug . '.html';
        $target = $this->rootPath . '/' . $path;

        if (is_file($target)) {
            throw new RuntimeException('That page already exists.');
        }

        $html = $this->renderKind(
            'page',
            $this->themes->currentThemeId(),
            [
                'path' => $path,
                'title' => $title,
                'excerpt' => 'This page was generated by WYSiteIWYG and can be edited in place from /edit/.',
                'hashtags' => '',
                'main_menu' => $this->currentMenuHtml(),
                'page_content_blocks' => [
                    $this->defaultPageContentSecondary($title, 'Introduce this page with a short overview or lead paragraph.'),
                    $this->defaultPageContent(),
                    $this->defaultPageSupportingContent(),
                ],
            ],
            '/assets/site.css'
        );

        Filesystem::ensureDirectory(dirname($target));
        Filesystem::atomicWrite($target, $html);
        return $path;
    }

    public function importExistingPage(string $relativePath, array $options = []): void
    {
        $candidate = $this->repository->getImportCandidate($relativePath);
        $meta = $candidate['meta'];
        $title = trim((string) ($options['title'] ?? ($meta['title'] ?? $candidate['title'] ?? basename($relativePath))));
        $excerpt = trim((string) ($options['excerpt'] ?? ($meta['excerpt'] ?? $candidate['excerpt'] ?? '')));
        $containerXPath = trim((string) ($options['container_xpath'] ?? ''));
        $blockXpaths = array_values(
            array_filter(
                array_map(
                    static fn(string $value): string => trim($value),
                    $options['block_xpaths'] ?? []
                ),
                static fn(string $value): bool => $value !== ''
            )
        );

        $blocks = $this->extractImportedPageBlocks($candidate['html'], $containerXPath, $blockXpaths);
        if ($blocks === []) {
            $blocks = [$this->defaultPageContent()];
        }

        $html = $this->renderKind(
            'page',
            $this->themes->currentThemeId(),
            [
                'path' => $relativePath,
                'title' => $title !== '' ? $title : basename($relativePath),
                'excerpt' => $excerpt,
                'hashtags' => '',
                'main_menu' => $this->currentMenuHtml(),
                'page_content_blocks' => $blocks,
            ],
            '/assets/site.css'
        );

        Filesystem::atomicWrite($this->rootPath . '/' . ltrim($relativePath, '/'), $html);
    }

    public function createBlogPost(string $title, string $slug, string $excerpt, string $hashtags = '#blog'): string
    {
        $title = trim($title);
        $excerpt = trim($excerpt);
        $slug = $this->normalizeFlatSlug($slug !== '' ? $slug : $title);
        $tags = $this->normalizeTagList($hashtags !== '' ? $hashtags : '#blog');
        if ($tags === []) {
            $tags = ['blog'];
        }

        $path = $slug . '.html';
        $target = $this->rootPath . '/' . $path;

        if (is_file($target)) {
            throw new RuntimeException('That blog post already exists.');
        }

        $html = $this->renderKind(
            'blog-post',
            $this->themes->currentThemeId(),
            [
                'path' => $path,
                'title' => $title,
                'excerpt' => $excerpt,
                'date' => gmdate('Y-m-d'),
                'hashtags' => $this->hashtagsString($tags),
                'main_menu' => $this->currentMenuHtml(),
                'tag_links' => $this->renderTagLinks($tags),
                'blog_post_content' => '<p>This is a new post generated by WYSiteIWYG.</p><p>Replace this content directly on the preview page and your edits will be written back into the static file on disk.</p>',
            ],
            '/assets/site.css'
        );

        Filesystem::atomicWrite($target, $html);
        $this->rebuildTagPages();

        return $path;
    }

    public function rebuildBlogIndex(?string $themeId = null, ?string $cssHref = null): void
    {
        $this->rebuildTagPages($themeId, $cssHref);
    }

    public function rebuildTagPages(?string $themeId = null, ?string $cssHref = null): void
    {
        $themeId ??= $this->themes->currentThemeId();
        $cssHref ??= '/assets/site.css';

        $pages = $this->repository->listPages();
        $tags = ['blog' => true];

        foreach ($pages as $page) {
            foreach ($page['tags'] as $tag) {
                $tags[$tag] = true;
            }

            if (($page['generated'] ?? '') === 'tag-index' && ($page['tag'] ?? '') !== '') {
                $tags[$page['tag']] = true;
            }
        }

        ksort($tags);

        foreach (array_keys($tags) as $tag) {
            $path = $this->tagPagePath($tag);
            $this->assertTagPathIsWritable($tag, $path);
            $existing = is_file($this->rootPath . '/' . $path) ? $this->repository->getPage($path) : null;

            $html = $this->renderKind(
                'blog',
                $themeId,
                [
                    'path' => $path,
                    'title' => $existing['meta']['title'] ?? $this->defaultTagTitle($tag),
                    'excerpt' => $existing['meta']['excerpt'] ?? $this->defaultTagExcerpt($tag),
                    'tag' => $tag,
                    'tag_label' => $this->tagLabel($tag),
                    'main_menu' => $this->normalizeMenuHtml($this->extractBlockContent($existing, 'main-menu') ?? $this->currentMenuHtml()),
                    'blog_index_content' => $this->normalizePageBlockContent($this->extractBlockContent($existing, 'blog-index-content')) ?: $this->defaultTagIntroContent($tag),
                    'blog_items' => $this->renderBlogItems($tag),
                ],
                $cssHref
            );

            Filesystem::ensureDirectory(dirname($this->rootPath . '/' . $path));
            Filesystem::atomicWrite($this->rootPath . '/' . $path, $html);
        }
    }

    public function syncMenu(string $menuHtml): void
    {
        $menuHtml = $this->normalizeMenuHtml($menuHtml);

        foreach ($this->repository->listPages() as $page) {
            foreach ($page['blocks'] as $block) {
                if ($block['name'] === 'main-menu') {
                    $this->repository->updateBlock($page['path'], 'main-menu', $menuHtml);
                    break;
                }
            }
        }

        $this->syncMenuIntoActiveTemplates($menuHtml);
    }

    public function availableThemes(): array
    {
        return $this->themes->listThemes();
    }

    public function currentTheme(): array
    {
        return $this->themes->currentTheme();
    }

    public function renderPageForTheme(string $relativePath, string $themeId, string $cssHref): string
    {
        $page = $this->repository->getPage($relativePath);
        return $this->renderPage(
            $relativePath,
            $themeId,
            $cssHref,
            $this->themes->loadTemplate($themeId, $this->themeTemplateKind($page['kind']))
        );
    }

    public function renderPageForActiveTemplate(string $relativePath): string
    {
        return $this->renderPage(
            $relativePath,
            $this->themes->currentThemeId(),
            '/assets/site.css'
        );
    }

    /**
     * Deploy the documentation/demo content (see edit/docs/content.php) as real,
     * editable, location-agnostic WYSite pages at the site root. Pages are flagged
     * demo="1" so they can later be removed with deleteDemoContent(). Existing
     * non-demo pages are not rebuilt, so dropping the editor into an existing site
     * and then deploying the demo does not rewrite the user's own pages.
     *
     * @param array{menu?:string,pages?:array,posts?:array} $content
     * @return int number of pages/posts newly created
     */
    public function deployDemoSite(array $content): int
    {
        $menu = (string) ($content['menu'] ?? '');
        $created = 0;

        $this->ensurePublishedStylesheet();

        foreach (($content['pages'] ?? []) as $spec) {
            $created += $this->deployDemoPage($spec, $menu);
        }

        foreach (($content['posts'] ?? []) as $spec) {
            $created += $this->deployDemoPost($spec, $menu);
        }

        // Build the generated blog/tag landing pages from the demo posts. By now
        // the demo pages carry the demo menu, so currentMenuHtml() feeds it in.
        $this->rebuildTagPages();

        // Flag demo content last: rebuilds/renders regenerate the META comment from
        // the template and would otherwise drop the flag.
        foreach (($content['pages'] ?? []) as $spec) {
            $this->repository->updateMetadata($this->pagePathForSlug((string) $spec['slug']), ['demo' => '1']);
        }
        foreach (($content['posts'] ?? []) as $spec) {
            $this->repository->updateMetadata($spec['slug'] . '.html', ['demo' => '1']);
        }

        return $created;
    }

    private function deployDemoPage(array $spec, string $menu): int
    {
        $slug = (string) $spec['slug'];
        $path = $this->pagePathForSlug($slug);
        $created = 0;

        if (!is_file($this->rootPath . '/' . $path)) {
            $this->createPage((string) $spec['title'], $slug);
            $created = 1;
        }

        $this->repository->updateMetadata($path, [
            'title' => (string) $spec['title'],
            'excerpt' => (string) ($spec['excerpt'] ?? ''),
        ]);

        $names = ['page-content', 'page-content-2', 'page-content-3'];
        foreach (array_values($spec['blocks'] ?? []) as $index => $html) {
            if (isset($names[$index])) {
                $this->repository->updateBlock($path, $names[$index], (string) $html);
            }
        }

        if ($menu !== '') {
            $this->repository->updateBlock($path, 'main-menu', $this->normalizeMenuHtml($menu));
        }

        // Re-render through the active template so the content and menu we just
        // wrote raw are localized for the current deployment location.
        Filesystem::atomicWrite($this->rootPath . '/' . $path, $this->renderPageForActiveTemplate($path));

        return $created;
    }

    private function deployDemoPost(array $spec, string $menu): int
    {
        $slug = (string) $spec['slug'];
        $path = $slug . '.html';
        $created = 0;

        if (!is_file($this->rootPath . '/' . $path)) {
            $this->createBlogPost(
                (string) $spec['title'],
                $slug,
                (string) ($spec['excerpt'] ?? ''),
                (string) ($spec['hashtags'] ?? '#blog')
            );
            $created = 1;
        }

        $this->repository->updateMetadata($path, [
            'title' => (string) $spec['title'],
            'excerpt' => (string) ($spec['excerpt'] ?? ''),
            'hashtags' => (string) ($spec['hashtags'] ?? '#blog'),
        ]);
        $this->repository->updateBlock($path, 'blog-post-content', (string) $spec['content']);

        if ($menu !== '') {
            $this->repository->updateBlock($path, 'main-menu', $this->normalizeMenuHtml($menu));
        }

        Filesystem::atomicWrite($this->rootPath . '/' . $path, $this->renderPageForActiveTemplate($path));

        return $created;
    }

    private function pagePathForSlug(string $slug): string
    {
        return $slug === 'index' ? 'index.html' : $slug . '.html';
    }

    private function ensurePublishedStylesheet(): void
    {
        $target = $this->rootPath . '/assets/site.css';
        if (is_file($target)) {
            return;
        }

        $css = $this->themes->loadStylesheet($this->themes->currentThemeId());
        Filesystem::ensureDirectory(dirname($target));
        Filesystem::atomicWrite($target, $this->localizeStylesheet($css));
    }

    public function hasDemoContent(): bool
    {
        foreach ($this->repository->listPages() as $page) {
            if (!empty($page['demo'])) {
                return true;
            }
        }

        return false;
    }

    /**
     * Remove every page that was generated as demo content (flagged demo="1"),
     * along with the generated tag/blog landing pages those demo posts produced.
     * Landing pages are regenerated afterwards only if real posts remain.
     */
    public function deleteDemoContent(): int
    {
        $removed = 0;
        $dirs = [];

        foreach ($this->repository->listPages() as $page) {
            $isDemo = !empty($page['demo']);
            $isGeneratedLanding = ($page['generated'] ?? '') === 'tag-index';
            if (!$isDemo && !$isGeneratedLanding) {
                continue;
            }

            $full = $this->rootPath . '/' . ltrim((string) $page['path'], '/');
            if (is_file($full) && @unlink($full)) {
                $dirs[dirname($full)] = true;
                if ($isDemo) {
                    $removed++;
                }
            }
        }

        foreach (array_keys($dirs) as $dir) {
            if ($dir !== $this->rootPath && is_dir($dir) && $this->isEmptyDirectory($dir)) {
                @rmdir($dir);
            }
        }

        // Only rebuild landing pages if genuine (non-demo) posts still exist;
        // otherwise we would resurrect an empty blog index.
        if ($this->repository->listBlogPosts() !== []) {
            $this->rebuildTagPages();
        }

        return $removed;
    }

    /**
     * Remove every HTML page from the site (managed and unmanaged), then prune any
     * directories left empty. Assets (images, imported media, stylesheets) and the
     * /edit/ app are left in place. Returns the number of pages removed. This is the
     * "start from a clean site" reset.
     */
    public function purgeAllPages(): int
    {
        $removed = 0;
        $dirs = [];

        $iterator = new \RecursiveIteratorIterator(
            new \RecursiveDirectoryIterator($this->rootPath, \FilesystemIterator::SKIP_DOTS),
            \RecursiveIteratorIterator::LEAVES_ONLY
        );

        foreach ($iterator as $file) {
            if (!$file->isFile()) {
                continue;
            }

            $full = str_replace('\\', '/', $file->getPathname());
            $rel = ltrim(substr($full, strlen($this->rootPath)), '/');
            if ($rel === '' || str_starts_with($rel, 'edit/')) {
                continue;
            }

            $ext = strtolower((string) pathinfo($rel, PATHINFO_EXTENSION));
            if (!in_array($ext, ['html', 'htm'], true)) {
                continue;
            }

            if (@unlink($full)) {
                $dirs[dirname($full)] = true;
                $removed++;
            }
        }

        // Prune directories emptied by the deletion (deepest first), never the root.
        $dirList = array_keys($dirs);
        usort($dirList, static fn(string $a, string $b): int => strlen($b) <=> strlen($a));
        foreach ($dirList as $dir) {
            if ($dir !== $this->rootPath && is_dir($dir) && $this->isEmptyDirectory($dir)) {
                @rmdir($dir);
            }
        }

        return $removed;
    }

    private function isEmptyDirectory(string $dir): bool
    {
        $entries = @scandir($dir);
        if ($entries === false) {
            return false;
        }

        return array_values(array_diff($entries, ['.', '..'])) === [];
    }

    public function rebuildPagesUsingTemplate(string $kind): int
    {
        $updated = 0;

        foreach ($this->repository->listPages() as $pageInfo) {
            if (($pageInfo['kind'] ?? '') !== $kind) {
                continue;
            }

            if (!empty($pageInfo['exclude_template'])) {
                continue;
            }

            $html = $this->renderPageForActiveTemplate($pageInfo['path']);
            Filesystem::atomicWrite($this->rootPath . '/' . $pageInfo['path'], $html);
            $updated++;
        }

        return $updated;
    }

    private function renderPage(string $relativePath, string $themeId, string $cssHref, ?string $template = null): string
    {
        $page = $this->repository->getPage($relativePath);
        $meta = $page['meta'];
        $tags = $this->normalizeTagList((string) ($meta['hashtags'] ?? ''));
        $tag = (string) ($meta['tag'] ?? '');

        return $this->renderKind(
            $page['kind'],
            $themeId,
            [
                'path' => $relativePath,
                'title' => $meta['title'] ?? basename($relativePath),
                'excerpt' => $meta['excerpt'] ?? '',
                'date' => $meta['date'] ?? gmdate('Y-m-d'),
                'hashtags' => $this->hashtagsString($tags),
                'tag' => $tag,
                'tag_label' => $tag !== '' ? $this->tagLabel($tag) : 'Journal',
                'main_menu' => $this->normalizeMenuHtml($this->extractBlockContent($page, 'main-menu') ?? $this->currentMenuHtml()),
                'page_content_blocks' => $this->pageContentBlocksForPage($page, $meta['title'] ?? basename($relativePath), $meta['excerpt'] ?? ''),
                'blog_post_content' => $this->normalizePostBlockContent($this->extractBlockContent($page, 'blog-post-content')) ?: $this->normalizePostBlockContent($this->extractBlockContent($page, 'page-content')) ?: $this->defaultBlogPostContent(),
                'blog_index_content' => $this->normalizePageBlockContent($this->extractBlockContent($page, 'blog-index-content')) ?: $this->defaultTagIntroContent($tag !== '' ? $tag : 'blog'),
                'blog_items' => $this->renderBlogItems($tag !== '' ? $tag : 'blog'),
                'tag_links' => $this->renderTagLinks($tags),
            ],
            $cssHref,
            $template
        );
    }

    public function applyTheme(string $themeId): void
    {
        $this->themes->assertThemeIsValid($themeId);
        $this->publishThemeScaffold($themeId, $this->currentMenuHtml());

        foreach ($this->repository->listPages() as $pageInfo) {
            if (!empty($pageInfo['exclude_template'])) {
                continue;
            }

            $html = $this->renderPageForTheme($pageInfo['path'], $themeId, '/assets/site.css');
            Filesystem::atomicWrite($this->rootPath . '/' . $pageInfo['path'], $html);
        }

        $this->rebuildTagPages($themeId, '/assets/site.css');
        $this->themes->setCurrentTheme($themeId);
    }

    public function normalizeMenuHtml(string $menuHtml): string
    {
        $menuHtml = trim($menuHtml);
        if ($menuHtml === '') {
            return '<ul class="main-menu"><li><a href="/">Home</a></li><li><a href="/blog/">Blog</a></li></ul>';
        }

        if (class_exists(\DOMDocument::class)) {
            $dom = new \DOMDocument('1.0', 'UTF-8');
            libxml_use_internal_errors(true);
            $dom->loadHTML(
                '<!doctype html><html><body>' . $menuHtml . '</body></html>',
                LIBXML_HTML_NOIMPLIED | LIBXML_HTML_NODEFDTD
            );
            libxml_clear_errors();

            $body = $dom->getElementsByTagName('body')->item(0);
            if ($body instanceof \DOMElement) {
                $list = null;
                foreach (['ul', 'ol'] as $tag) {
                    $candidate = $body->getElementsByTagName($tag)->item(0);
                    if ($candidate instanceof \DOMElement) {
                        $list = $candidate;
                        break;
                    }
                }

                if ($list instanceof \DOMElement) {
                    $classNames = preg_split('/\s+/', trim($list->getAttribute('class'))) ?: [];
                    if (!in_array('main-menu', $classNames, true)) {
                        $classNames[] = 'main-menu';
                    }
                    $classNames = array_values(array_filter($classNames, static fn(string $name): bool => $name !== ''));
                    $list->setAttribute('class', implode(' ', $classNames));
                    return trim($dom->saveHTML($list) ?: $menuHtml);
                }
            }
        }

        if (preg_match('/<\s*(ul|ol)\b([^>]*)>/i', $menuHtml, $match, PREG_OFFSET_CAPTURE) === 1) {
            $tag = $match[1][0];
            $attrs = $match[2][0];
            $offset = $match[0][1];
            $length = strlen($match[0][0]);

            if (preg_match('/\bclass\s*=\s*"([^"]*)"/i', $attrs, $classMatch) === 1) {
                $classes = preg_split('/\s+/', trim($classMatch[1])) ?: [];
                if (!in_array('main-menu', $classes, true)) {
                    $classes[] = 'main-menu';
                }
                $replacement = '<' . $tag . preg_replace(
                    '/\bclass\s*=\s*"([^"]*)"/i',
                    'class="' . h(implode(' ', array_filter($classes))) . '"',
                    $attrs,
                    1
                ) . '>';
            } else {
                $replacement = '<' . $tag . ' class="main-menu"' . $attrs . '>';
            }

            return substr_replace($menuHtml, $replacement, $offset, $length);
        }

        return '<ul class="main-menu"><li>' . $menuHtml . '</li></ul>';
    }

    private function publishThemeScaffold(string $themeId, string $menuHtml): void
    {
        $templateTargets = [
            'page' => $this->repository->activeTemplateRelativePath('page'),
            'blog-post' => $this->repository->activeTemplateRelativePath('blog-post'),
            'blog' => $this->repository->activeTemplateRelativePath('blog'),
        ];

        foreach ($templateTargets as $kind => $target) {
            $raw = $this->themes->loadTemplate($themeId, $kind);
            $rendered = str_replace(
                ['{{THEME_CSS_HREF}}', '{{MAIN_MENU}}'],
                ['/assets/site.css', trim($menuHtml)],
                $raw
            );
            Filesystem::atomicWrite($this->rootPath . '/' . $target, $rendered);
        }

        Filesystem::atomicWrite(
            $this->rootPath . '/assets/site.css',
            $this->localizeStylesheet($this->themes->loadStylesheet($themeId))
        );
    }

    /**
     * Localize url(...) references in the published stylesheet. The file is
     * served from <site-root>/assets/site.css, so site-internal absolute URLs
     * become relative to that location (one directory below the site root).
     */
    private function localizeStylesheet(string $css): string
    {
        // The published stylesheet lives at <root>/assets/site.css.
        return UrlLocalizer::localizeCssUrls($css, 'assets', $this->siteBaseUrl);
    }

    private function syncMenuIntoActiveTemplates(string $menuHtml): void
    {
        foreach (['home', 'page', 'blog-post', 'blog'] as $kind) {
            try {
                $this->repository->updateBlockInRelativeFile(
                    $this->repository->activeTemplateRelativePath($kind),
                    'main-menu',
                    $menuHtml
                );
            } catch (RuntimeException) {
                continue;
            }
        }
    }

    private function renderKind(string $kind, string $themeId, array $data, string $cssHref, ?string $template = null): string
    {
        $template ??= $this->loadActiveTemplateOrTheme($kind, $themeId);
        $pageContentBlocks = $data['page_content_blocks']
            ?? array_values(
                array_filter(
                    [
                        trim((string) ($data['page_content'] ?? '')),
                        trim((string) ($data['page_content_2'] ?? '')),
                        trim((string) ($data['page_content_3'] ?? '')),
                    ],
                    static fn(string $block): bool => $block !== ''
                )
            );

        if ($kind === 'page') {
            $template = $this->injectPageContentSlots($template, $pageContentBlocks);
        }

        // Scalar tokens carry plain text (page titles, excerpts, dates, tags) that
        // originates from editors or imported pages, and land in sensitive spots
        // like <title> and content="..." attributes. They are HTML-escaped here so
        // metadata can never inject markup/script into the generated public pages.
        // HTML-bearing tokens (MAIN_MENU, PAGE_CONTENT*, BLOG_*, TAG_LINKS) are the
        // editor's own sanitized block output and stay raw.
        $replacements = [
            '{{THEME_CSS_HREF}}' => $cssHref,
            '{{TITLE}}' => h((string) ($data['title'] ?? 'Untitled')),
            '{{EXCERPT}}' => h((string) ($data['excerpt'] ?? '')),
            '{{DATE}}' => h((string) ($data['date'] ?? gmdate('Y-m-d'))),
            '{{BODY_CLASS}}' => h($this->bodyClass($data['path'] ?? 'index.html', $kind)),
            '{{MAIN_MENU}}' => trim((string) ($data['main_menu'] ?? $this->currentMenuHtml())),
            '{{PAGE_CONTENT_BLOCKS}}' => $kind === 'page' ? '' : $this->renderPageContentBlocks($pageContentBlocks),
            '{{PAGE_CONTENT_BLOCK}}' => '',
            '{{PAGE_CONTENT}}' => trim((string) ($pageContentBlocks[0] ?? $data['page_content'] ?? '')),
            '{{PAGE_CONTENT_2}}' => trim((string) ($pageContentBlocks[1] ?? $data['page_content_2'] ?? '')),
            '{{PAGE_CONTENT_3}}' => trim((string) ($pageContentBlocks[2] ?? $data['page_content_3'] ?? '')),
            '{{BLOG_POST_CONTENT}}' => trim((string) ($data['blog_post_content'] ?? '')),
            '{{BLOG_INDEX_CONTENT}}' => trim((string) ($data['blog_index_content'] ?? '')),
            '{{BLOG_ITEMS}}' => trim((string) ($data['blog_items'] ?? '')),
            '{{HASHTAGS}}' => h(trim((string) ($data['hashtags'] ?? ''))),
            '{{TAG_LINKS}}' => trim((string) ($data['tag_links'] ?? '')),
            '{{TAG}}' => h(trim((string) ($data['tag'] ?? ''))),
            '{{TAG_LABEL}}' => h(trim((string) ($data['tag_label'] ?? 'Journal'))),
            '{{WYSITE_PUBLIC_BRIDGE}}' => $this->publicBridgeHtml(),
        ];

        $html = str_replace(array_keys($replacements), array_values($replacements), $template);

        return $this->localizeUrls($html, (string) ($data['path'] ?? 'index.html'));
    }

    private function loadActiveTemplateOrTheme(string $kind, string $themeId): string
    {
        foreach ($this->activeTemplateKindChain($kind) as $candidate) {
            try {
                return $this->repository->loadActiveTemplate($candidate);
            } catch (RuntimeException) {
                continue;
            }
        }

        return $this->themes->loadTemplate($themeId, $this->themeTemplateKind($kind));
    }

    /** A 'home' page uses an active home template if present, else falls back to 'page'. */
    private function activeTemplateKindChain(string $kind): array
    {
        return $kind === 'home' ? ['home', 'page'] : [$kind];
    }

    /** Themes do not ship a 'home' template; home pages render with the page template. */
    private function themeTemplateKind(string $kind): string
    {
        return $kind === 'home' ? 'page' : $kind;
    }

    private function renderBlogItems(string $tag): string
    {
        $cards = array_map(
            function (array $post) use ($tag): string {
                $date = $post['date'] !== '' ? date('F j, Y', strtotime($post['date'])) : '';
                return '<article class="blog-card">' .
                    '<p class="blog-card__meta">' . h($date) . '</p>' .
                    '<h2><a href="' . h($post['url']) . '">' . h($post['title']) . '</a></h2>' .
                    '<p>' . h($post['excerpt']) . '</p>' .
                    $this->renderTagLinks($post['tags'], $tag) .
                    '<p><a class="text-link" href="' . h($post['url']) . '">Read the post</a></p>' .
                    '</article>';
            },
            $this->repository->listBlogPosts($tag)
        );

        if ($cards === []) {
            return '<article class="blog-card"><h2>No posts yet</h2><p>Add the <code>#' . h($tag) . '</code> hashtag to a post and it will appear here automatically.</p></article>';
        }

        return implode("\n", $cards);
    }

    private function renderTagLinks(array $tags, ?string $activeTag = null): string
    {
        if ($tags === []) {
            return '';
        }

        $links = array_map(
            function (string $tag) use ($activeTag): string {
                $class = 'tag-chip';
                if ($activeTag !== null && $activeTag === $tag) {
                    $class .= ' is-active';
                }

                return '<a class="' . h($class) . '" href="' . h($this->tagPageUrl($tag)) . '">#' . h($tag) . '</a>';
            },
            $tags
        );

        return '<div class="tag-links">' . implode('', $links) . '</div>';
    }

    private function currentMenuHtml(): string
    {
        foreach ($this->repository->listPages() as $page) {
            foreach ($page['blocks'] as $block) {
                if ($block['name'] === 'main-menu') {
                    return $this->normalizeMenuHtml($this->repository->getBlock($page['path'], 'main-menu')['content']);
                }
            }
        }

        return '<ul class="main-menu"><li><a href="/">Home</a></li><li><a href="/blog/">Blog</a></li></ul>';
    }

    private function extractBlockContent(?array $page, string $name): ?string
    {
        if ($page === null) {
            return null;
        }

        foreach ($page['blocks'] as $block) {
            if ($block['name'] === $name) {
                return $block['content'];
            }
        }

        return null;
    }

    private function bodyClass(string $path, string $kind): string
    {
        $clean = trim(str_replace('/', '-', $path), '-');
        $clean = preg_replace('/\.html?$/i', '', $clean) ?? $clean;
        if ($clean === '') {
            $clean = 'index';
        }

        return $kind . '-' . $clean;
    }

    private function defaultPageContentSecondary(string $title, string $excerpt): string
    {
        $copy = $excerpt !== '' ? $excerpt : 'Use this lead section for a short introduction, summary, or callout before the main body begins.';
        return '<h2>Overview</h2><p>' . h($copy) . '</p>';
    }

    private function defaultPageContent(): string
    {
        return '<p>Start writing here. The content inside this marker block is directly editable in the transparent ProseMirror editor.</p><p>You can add headings, lists, tables, links, and images without leaving the live page preview.</p>';
    }

    private function defaultPageSupportingContent(): string
    {
        return '<h2>Supporting Section</h2><p>This is a second editable region, useful for side notes, grouped links, or a follow-up section farther down the page.</p>';
    }

    private function pageContentBlocksForPage(?array $page, string $title, string $excerpt): array
    {
        $blocks = [];

        if ($page !== null) {
            foreach ($page['blocks'] as $block) {
                if (
                    $block['name'] !== 'page-content'
                    && preg_match('/^page-content-\d+$/', $block['name']) !== 1
                ) {
                    continue;
                }

                $normalized = $this->normalizePageBlockContent($block['content']);
                if ($normalized !== '') {
                    $blocks[] = $normalized;
                }
            }
        }

        if ($blocks !== []) {
            return $blocks;
        }

        $fallback = $this->normalizePageBlockContent($this->extractBlockContent($page, 'blog-post-content'));
        if ($fallback !== '') {
            return [$fallback];
        }

        return [
            $this->defaultPageContentSecondary($title, $excerpt),
            $this->defaultPageContent(),
            $this->defaultPageSupportingContent(),
        ];
    }

    private function renderPageContentBlocks(array $blocks): string
    {
        $normalizedBlocks = array_values(
            array_filter(
                array_map(
                    static fn(string $block): string => trim($block),
                    $blocks
                ),
                static fn(string $block): bool => $block !== ''
            )
        );

        if ($normalizedBlocks === []) {
            $normalizedBlocks = [$this->defaultPageContent()];
        }

        $markup = [];
        foreach ($normalizedBlocks as $index => $blockHtml) {
            $blockName = $index === 0 ? 'page-content' : 'page-content-' . ($index + 1);
            $markup[] = '<section class="wysite-page-block">' .
                '<article class="content-block">' .
                '<div class="content-stack">' .
                "\n" . $this->renderSinglePageContentBlock($blockName, $blockHtml) .
                "\n" . '</div>' .
                '</article>' .
                '</section>';
        }

        return implode("\n\n", $markup);
    }

    private function injectPageContentSlots(string $template, array $blocks): string
    {
        $slotCount = substr_count($template, '{{PAGE_CONTENT_BLOCK}}');
        if ($slotCount < 1) {
            return str_replace('{{PAGE_CONTENT_BLOCKS}}', $this->renderPageContentBlocks($blocks), $template);
        }

        $distributedBlocks = $this->distributePageBlocksToSlots($blocks, $slotCount);
        $slotIndex = 0;

        $template = preg_replace_callback(
            '/\{\{PAGE_CONTENT_BLOCK\}\}/',
            function () use (&$slotIndex, $distributedBlocks): string {
                $blockName = $slotIndex === 0 ? 'page-content' : 'page-content-' . ($slotIndex + 1);
                $slotHtml = $distributedBlocks[$slotIndex] ?? '';
                $slotIndex++;

                return $this->renderSinglePageContentBlock($blockName, $slotHtml);
            },
            $template
        ) ?? $template;

        return str_replace('{{PAGE_CONTENT_BLOCKS}}', '', $template);
    }

    private function distributePageBlocksToSlots(array $blocks, int $slotCount): array
    {
        $normalizedBlocks = array_values(
            array_filter(
                array_map(
                    static fn(string $block): string => trim($block),
                    $blocks
                ),
                static fn(string $block): bool => $block !== ''
            )
        );

        if ($normalizedBlocks === []) {
            $normalizedBlocks = [$this->defaultPageContent()];
        }

        $slots = array_fill(0, $slotCount, '');
        foreach ($normalizedBlocks as $index => $blockHtml) {
            $slotIndex = min($index, $slotCount - 1);
            if ($slots[$slotIndex] !== '') {
                $slots[$slotIndex] .= "\n\n";
            }
            $slots[$slotIndex] .= $blockHtml;
        }

        return $slots;
    }

    private function renderSinglePageContentBlock(string $blockName, string $html): string
    {
        $html = trim($html);

        return '<!-- WYSITE:BEGIN name="' . $blockName . '" type="page" label="Page Content" -->' .
            ($html !== '' ? "\n" . $html . "\n" : "\n") .
            '<!-- WYSITE:END name="' . $blockName . '" -->';
    }

    private function publicBridgeHtml(): string
    {
        // Base-relative paths so the public live-edit banner resolves against the
        // page's own <base href>, working from any deployment subdirectory.
        return '<script>window.WYSITE_PUBLIC_CONTEXT={appUrl:"edit"};</script><script type="module" src="edit/assets/live-edit-banner.js"></script>';
    }

    /**
     * Make a generated page location-agnostic: convert site-internal absolute
     * URLs to base-relative ones and inject a per-page relative <base href> so
     * the static output works whether deployed at the domain root or in any
     * subdirectory, over http or https.
     */
    private function localizeUrls(string $html, string $relativePath): string
    {
        return UrlLocalizer::localizeHtml($html, $relativePath, $this->siteBaseUrl);
    }

    private function normalizePageBlockContent(?string $html): string
    {
        return $this->stripBlockWrappers($html, ['content-block', 'blog-card'], ['content-stack']);
    }

    private function normalizePostBlockContent(?string $html): string
    {
        return $this->stripBlockWrappers($html, ['content-block', 'blog-card'], ['post-body', 'content-stack']);
    }

    private function stripBlockWrappers(?string $html, array $outerClasses, array $innerClasses): string
    {
        $html = trim((string) $html);
        if ($html === '') {
            return '';
        }

        if (!class_exists(\DOMDocument::class)) {
            return $html;
        }

        $dom = new \DOMDocument('1.0', 'UTF-8');
        libxml_use_internal_errors(true);
        $dom->loadHTML(
            '<!doctype html><html><body>' . $html . '</body></html>',
            LIBXML_HTML_NOIMPLIED | LIBXML_HTML_NODEFDTD
        );
        libxml_clear_errors();

        $body = $dom->getElementsByTagName('body')->item(0);
        if (!($body instanceof \DOMElement)) {
            return $html;
        }

        $nodes = [];
        foreach ($body->childNodes as $child) {
            if ($child instanceof \DOMText && trim($child->textContent ?? '') === '') {
                continue;
            }
            $nodes[] = $child;
        }

        if (count($nodes) !== 1 || !($nodes[0] instanceof \DOMElement)) {
            return $html;
        }

        $outer = $nodes[0];
        if (!$this->elementHasAnyClass($outer, $outerClasses)) {
            return $html;
        }

        $children = [];
        foreach ($outer->childNodes as $child) {
            if ($child instanceof \DOMText && trim($child->textContent ?? '') === '') {
                continue;
            }
            $children[] = $child;
        }

        if (count($children) === 1 && $children[0] instanceof \DOMElement && $this->elementHasAnyClass($children[0], $innerClasses)) {
            return $this->innerHtml($children[0]);
        }

        return $this->innerHtml($outer);
    }

    private function elementHasAnyClass(\DOMElement $element, array $classes): bool
    {
        $tokens = preg_split('/\s+/', trim($element->getAttribute('class'))) ?: [];
        foreach ($classes as $class) {
            if (in_array($class, $tokens, true)) {
                return true;
            }
        }

        return false;
    }

    private function innerHtml(\DOMElement $element): string
    {
        $html = '';
        foreach ($element->childNodes as $child) {
            $html .= $element->ownerDocument?->saveHTML($child) ?? '';
        }

        return trim($html);
    }

    private function defaultBlogPostContent(): string
    {
        return '<p>This page is ready for a full post body.</p>';
    }

    private function extractImportedPageBlocks(string $html, string $containerXPath = '', array $blockXpaths = [], bool $stripChrome = true): array
    {
        $html = trim($html);
        if ($html === '') {
            return [];
        }

        if (!class_exists(\DOMDocument::class)) {
            return [$this->stripScripts($html)];
        }

        $dom = new \DOMDocument('1.0', 'UTF-8');
        libxml_use_internal_errors(true);
        $dom->loadHTML($html, LIBXML_HTML_NOIMPLIED | LIBXML_HTML_NODEFDTD);
        libxml_clear_errors();

        $xpath = new \DOMXPath($dom);
        $container = $this->resolveImportContainer($dom, $xpath, $containerXPath);

        // Remove site chrome (nav/header/footer) so a page imported into a theme
        // doesn't duplicate the menu/header/footer the theme template already
        // provides. The theme supplies those regions; only the page's own content
        // should land in the editable content block.
        if ($stripChrome) {
            $this->removeSiteChrome($dom, $container);
        }

        $containerHtml = $this->stripScripts($this->innerHtml($container));
        if ($containerHtml === '') {
            return [];
        }

        $queries = array_values(array_filter($blockXpaths, static fn(string $value): bool => trim($value) !== ''));
        if ($queries === []) {
            return [$containerHtml];
        }

        $selected = [];
        foreach ($queries as $query) {
            $nodes = $this->queryImportXPath($xpath, $container, $query);
            if ($nodes->length === 0) {
                throw new RuntimeException('The XPath "' . $query . '" did not match anything inside the import container.');
            }

            foreach ($nodes as $node) {
                if (!($node instanceof \DOMElement)) {
                    continue;
                }

                if ($node->parentNode !== $container) {
                    throw new RuntimeException('Each advanced placement XPath must match a direct child of the selected import container.');
                }

                $selected[spl_object_id($node)] = true;
            }
        }

        $blocks = [];
        $buffer = [];
        foreach ($container->childNodes as $child) {
            if ($child instanceof \DOMText && trim($child->textContent ?? '') === '') {
                continue;
            }

            $childHtml = trim($dom->saveHTML($child) ?: '');
            if ($childHtml === '') {
                continue;
            }

            $isStandaloneBlock = $child instanceof \DOMElement && isset($selected[spl_object_id($child)]);
            if ($isStandaloneBlock) {
                $bufferHtml = $this->stripScripts(trim(implode("\n", $buffer)));
                if ($bufferHtml !== '') {
                    $blocks[] = $bufferHtml;
                    $buffer = [];
                }

                $standaloneHtml = $this->stripScripts($childHtml);
                if ($standaloneHtml !== '') {
                    $blocks[] = $standaloneHtml;
                }
                continue;
            }

            $buffer[] = $childHtml;
        }

        $bufferHtml = $this->stripScripts(trim(implode("\n", $buffer)));
        if ($bufferHtml !== '') {
            $blocks[] = $bufferHtml;
        }

        return $blocks === [] ? [$containerHtml] : $blocks;
    }

    private function resolveImportContainer(\DOMDocument $dom, \DOMXPath $xpath, string $containerXPath): \DOMElement
    {
        $containerXPath = trim($containerXPath);
        if ($containerXPath !== '') {
            $nodes = $this->queryImportXPath($xpath, $dom, $containerXPath);
            foreach ($nodes as $node) {
                if ($node instanceof \DOMElement) {
                    return $node;
                }
            }

            throw new RuntimeException('The import container XPath did not match any element.');
        }

        // Prefer an explicit main-content landmark; these exclude site chrome.
        foreach (["//main[1]", "//*[@role='main'][1]"] as $query) {
            $nodes = $xpath->query($query);
            if ($nodes !== false && $nodes->length > 0 && $nodes->item(0) instanceof \DOMElement) {
                return $nodes->item(0);
            }
        }

        $body = $dom->getElementsByTagName('body')->item(0);
        if ($body instanceof \DOMElement) {
            return $body;
        }

        $documentElement = $dom->documentElement;
        if ($documentElement instanceof \DOMElement) {
            return $documentElement;
        }

        throw new RuntimeException('Unable to determine which part of the HTML document to import.');
    }

    /**
     * Remove page-level site chrome (navigation, banner header, footer) from within
     * an import container, wherever it sits — as a direct child of body or nested in
     * a layout wrapper. Content-level headers/footers (inside <article>) are kept, as
     * are the elements a theme legitimately needs; only the site's own repeated
     * navigation/header/footer are stripped so the theme's versions aren't doubled.
     */
    private function removeSiteChrome(\DOMDocument $dom, \DOMElement $container): void
    {
        $xpath = new \DOMXPath($dom);
        $remove = [];

        // Navigation and ARIA landmark chrome, anywhere in the container.
        $landmarks = $xpath->query(
            ".//nav | .//*[@role='navigation'] | .//*[@role='banner'] | .//*[@role='contentinfo']",
            $container
        );
        if ($landmarks !== false) {
            foreach ($landmarks as $element) {
                if ($element instanceof \DOMElement) {
                    $remove[] = $element;
                }
            }
        }

        // Page-level <header>/<footer> (those not inside an <article>).
        $headerFooters = $xpath->query('.//header | .//footer', $container);
        if ($headerFooters !== false) {
            foreach ($headerFooters as $element) {
                if (!$element instanceof \DOMElement) {
                    continue;
                }
                $ancestors = $xpath->query('ancestor::article', $element);
                if ($ancestors === false || $ancestors->length === 0) {
                    $remove[] = $element;
                }
            }
        }

        // Common non-semantic chrome wrappers, matched conservatively by id/class.
        $chromeTokens = [
            'site-header', 'masthead', 'site-footer', 'colophon', 'site-navigation',
            'main-navigation', 'primary-navigation', 'top-bar', 'topbar', 'site-branding',
        ];
        $divs = $xpath->query('.//div | .//section', $container);
        if ($divs !== false) {
            foreach ($divs as $element) {
                if (!$element instanceof \DOMElement) {
                    continue;
                }
                $tokens = array_map(
                    'strtolower',
                    preg_split('/\s+/', trim($element->getAttribute('class') . ' ' . $element->getAttribute('id'))) ?: []
                );
                if (array_intersect($tokens, $chromeTokens) !== []) {
                    $remove[] = $element;
                }
            }
        }

        foreach ($remove as $element) {
            if ($element->parentNode instanceof \DOMNode) {
                $element->parentNode->removeChild($element);
            }
        }
    }

    private function queryImportXPath(\DOMXPath $xpath, \DOMNode $contextNode, string $query): \DOMNodeList
    {
        $result = str_starts_with($query, '/')
            ? $xpath->query($query)
            : $xpath->query($query, $contextNode);

        if ($result === false) {
            throw new RuntimeException('The XPath "' . $query . '" is not valid.');
        }

        return $result;
    }

    private function stripScripts(string $html): string
    {
        $html = trim($html);
        if ($html === '') {
            return '';
        }

        if (!class_exists(\DOMDocument::class)) {
            return trim(preg_replace('/<script\b[^>]*>.*?<\/script>/is', '', $html) ?? $html);
        }

        $dom = new \DOMDocument('1.0', 'UTF-8');
        libxml_use_internal_errors(true);
        $dom->loadHTML(
            '<!doctype html><html><body>' . $html . '</body></html>',
            LIBXML_HTML_NOIMPLIED | LIBXML_HTML_NODEFDTD
        );
        libxml_clear_errors();

        while (($scripts = $dom->getElementsByTagName('script'))->length > 0) {
            $script = $scripts->item(0);
            $script?->parentNode?->removeChild($script);
        }

        $body = $dom->getElementsByTagName('body')->item(0);
        if (!($body instanceof \DOMElement)) {
            return $html;
        }

        return trim($this->innerHtml($body));
    }

    private function defaultTagIntroContent(string $tag): string
    {
        if ($tag === 'blog') {
            return '<h2>The main journal feed</h2><p>This landing page gathers every post tagged <code>#blog</code>. Add more hashtags to any post and WYSiteIWYG will generate matching tag pages automatically.</p>';
        }

        return '<h2>#' . h($tag) . '</h2><p>This landing page is generated automatically from posts tagged <code>#' . h($tag) . '</code>.</p>';
    }

    private function defaultTagTitle(string $tag): string
    {
        return $tag === 'blog' ? 'Journal' : ucfirst(str_replace('-', ' ', $tag));
    }

    private function defaultTagExcerpt(string $tag): string
    {
        return $tag === 'blog'
            ? 'Notes, updates, and posts collected under the default #blog hashtag.'
            : 'Posts collected under the #' . $tag . ' hashtag.';
    }

    private function tagLabel(string $tag): string
    {
        return $tag === 'blog' ? 'Journal' : 'Tag Archive';
    }

    private function tagPagePath(string $tag): string
    {
        return $tag === 'blog' ? 'blog/index.html' : $tag . '/index.html';
    }

    private function tagPageUrl(string $tag): string
    {
        return $tag === 'blog' ? '/blog/' : '/' . $tag . '/';
    }

    private function hashtagsString(array $tags): string
    {
        if ($tags === []) {
            return '';
        }

        return implode(' ', array_map(static fn(string $tag): string => '#' . $tag, $tags));
    }

    private function normalizeTagList(string $value): array
    {
        $parts = preg_split('/[\s,]+/', trim($value)) ?: [];
        $tags = [];

        foreach ($parts as $part) {
            $tag = $this->normalizeTag($part);
            if ($tag === '' || in_array($tag, $tags, true)) {
                continue;
            }

            $tags[] = $tag;
        }

        return $tags;
    }

    private function normalizeTag(string $value): string
    {
        $value = ltrim(trim(strtolower($value)), '#');
        $value = preg_replace('/[^a-z0-9-]+/', '-', $value) ?? $value;
        $value = preg_replace('/-+/', '-', $value) ?? $value;
        $value = trim($value, '-');

        if ($value === '' || in_array($value, ['edit', 'assets', 'templates'], true)) {
            return '';
        }

        return $value;
    }

    private function assertTagPathIsWritable(string $tag, string $path): void
    {
        $conflictingFlatPage = $this->rootPath . '/' . $tag . '.html';
        if (is_file($conflictingFlatPage)) {
            throw new RuntimeException('The #' . $tag . ' tag would conflict with the page ' . $tag . '.html. Choose a different tag slug.');
        }

        $target = $this->rootPath . '/' . $path;
        if (!is_file($target)) {
            return;
        }

        $existing = $this->repository->getPage($path);
        if (($existing['meta']['generated'] ?? '') !== 'tag-index') {
            throw new RuntimeException('The tag page path ' . $path . ' already exists and is not a generated hashtag landing page.');
        }
    }

    public function normalizeEditableBlockHtml(string $blockType, string $html): string
    {
        return match ($blockType) {
            'menu' => $this->normalizeMenuHtml($html),
            'blog-post' => $this->normalizePostBlockContent($html),
            'page', 'blog' => $this->normalizePageBlockContent($html),
            default => trim($html),
        };
    }

    private function normalizeSlug(string $value): string
    {
        $value = strtolower(trim($value));
        $value = preg_replace('/[^a-z0-9\/-]+/', '-', $value) ?? $value;
        $value = preg_replace('/-+/', '-', $value) ?? $value;
        $value = trim($value, '-/');

        if ($value === '') {
            throw new RuntimeException('Please provide a title or slug.');
        }

        if (str_contains($value, '../') || str_starts_with($value, 'edit')) {
            throw new RuntimeException('That slug is not allowed.');
        }

        return $value;
    }

    private function normalizeFlatSlug(string $value): string
    {
        $value = str_replace('/', '-', $value);
        return $this->normalizeSlug($value);
    }
}
